#  Introduction 

In [1]:
import pandas as pd
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)
a1.shape

(3,)

In [4]:
a2 = np.array( [ [1,2,3],
                 [4,5,6],
                [7,8,9]])
a2
a2.shape

(3, 3)

In [5]:
a3 = np.array([  [[1,2,3], 
                 [4,5,6],
                [7,8,9]],
               
                [[10,11,12],
                [13,14,15],
                [16,17,18] ] ] )

a3
     
a3.shape

(2, 3, 3)

In [6]:
a1.ndim, a2.ndim, a3.ndim 

(1, 2, 3)

In [7]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [8]:
a1.size, a2.size, a3.size

(3, 9, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating numpy Array

In [11]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [12]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((3,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(1,20)
random_array

9

In [35]:
#np.random.randint is for random integers between LOW (Include) and HIGH (Exclude) and 
# we can give a size such as the following example.

another_random_array = np.random.randint(1,20, size=(3,3))
another_random_array

array([[ 1, 10, 15],
       [15, 10,  3],
       [ 4,  8, 14]])

In [36]:
#random.random is between 0 and 1 with the size we give it. 

random_array2 = np.random.random ((5,3))
random_array2

array([[0.77516806, 0.78757005, 0.43474871],
       [0.16320699, 0.70249762, 0.90807914],
       [0.17368969, 0.168589  , 0.126867  ],
       [0.05054195, 0.8059953 , 0.29032125],
       [0.63228975, 0.18500443, 0.67440105]])

# Numpy random seed

In [45]:
# Pseudo-random numbers
#np.random.seed(seed = any number)
np.random.seed(0)
array_4 = np.random.randint(10, size=(5,3))
array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [46]:
#this is exactly the same as code before. 

np.random.seed(seed=0)
array_4 = np.random.randint(10, size=(5,3))
array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# Viewing Arrays

In [55]:
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
array_4[0] 

array([5, 0, 3])

In [57]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

# Manupulating & comparing arrays


## Arithmetic

In [66]:
a1

array([1, 2, 3])

In [68]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [69]:
a1 + ones 

array([2., 3., 4.])

In [70]:
a1 - ones

array([0., 1., 2.])

In [71]:
a2 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

## Aggregation

In [74]:
listy_list = [1,2,3]
type(listy_list)

list

In [75]:
sum(listy_list)

6

In [79]:
a1 

array([1, 2, 3])

In [80]:
type(a1)

numpy.ndarray

In [81]:
sum(a1)

6

In [82]:
np.sum(a1)

6

In [84]:
# creative a massive numpy array 
massive_array = np.random.random(100000)
massive_array.size

100000

In [85]:
massive_array[:10]

array([0.94802187, 0.71818603, 0.75389358, 0.10964897, 0.63814993,
       0.28945067, 0.361702  , 0.00315978, 0.04352426, 0.79419409])

In [89]:
%timeit sum(massive_array) 


3.63 ms ± 6.96 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [88]:
%timeit np.sum(massive_array)

20.1 µs ± 78.8 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [90]:
np.max(a2)

9

In [91]:
np.min(a2)

1

In [92]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
np.mean(a2)

5.0

In [94]:
np.var(a2)

6.666666666666667

In [95]:
np.std(a2)

2.581988897471611

In [97]:
np.sqrt(np.var(a2))

2.581988897471611

In [99]:
high = np.array([1,100,200,400,10000,30000])
high 

array([    1,   100,   200,   400, 10000, 30000])

# Transpose and Reshape

In [100]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
a2.shape

(3, 3)

In [106]:
a2.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [109]:
a2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [120]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [121]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [122]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [123]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [124]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [128]:
mat = mat2.T
mat

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [129]:
#dot product 
np.dot(mat1, mat)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Dot product example (Nut butter sales)

In [131]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [132]:
#create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amount, index=["Mond", "Tues","Wed"
                                                ,'Thurs',"Fri"], 
                                           columns =["Almond Butter", "Peanut Butter",'Cashew butter'])

weekly_sales

Almond Butter  Peanut Butter  Cashew butter
Mond              12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [165]:
price = np.array([10,8,12])


price.shape


(3,)

In [154]:
price

array([10,  8, 12])

In [163]:
price_data = pd.DataFrame(price.reshape(1,3), index =["Price"],
                         columns = ["Almond Butter", "Peanut Butter",'Cashew butter'])
price

array([10,  8, 12])

In [153]:
total_prices = price_data.dot(weekly_sales.T)
total_prices

Mond  Tues  Wed  Thurs  Fri
Price   240   138  458    232  142

In [156]:
weekly_sales.shape, price_data.T.shape

((5, 3), (3, 1))

((3,), (5, 3))

In [161]:
weekly_sales["Total"] = total_prices.T
weekly_sales

Almond Butter  Peanut Butter  Cashew butter  Total
Mond              12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

# Comparison operators 

In [166]:
a1

array([1, 2, 3])

In [167]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
a1 > a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [170]:
bool_array = a2 >= a1
bool_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [172]:
bool_array.dtype, type(bool_array)

(dtype('bool'), numpy.ndarray)

In [173]:
a1 > 5

array([False, False, False])

In [174]:
a2 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

# Sorting arrays

In [187]:
np.random.seed(0)
random_array = np.random.randint(10, size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [193]:
np.sort(random_array)  # organiza cada row

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [195]:
np.random.seed(0)
random_array = np.random.randint(10, size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [196]:
np.argsort(random_array)   #hay que arreglarlo 

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]])

In [197]:
a1

array([1, 2, 3])

In [198]:
np.argsort(a1)

array([0, 1, 2])

In [199]:
np.argmin(a1)  #entrega la posición donde está el menor

0

In [200]:
np.argmax(a1) 

2

In [ ]:
# Practical example - Numpy in Action